"""Убрал uuid на id в названиях полей с FK

Revision ID: ff2be026ad5f
Revises: ccb418f059c2
Create Date: 2025-08-11 09:39:41.497921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2be026ad5f'
down_revision: Union[str, Sequence[str], None] = 'ccb418f059c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('messages_sender_uuid_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'sender_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_uuid_fkey'), 'messages', 'users', ['sender_uuid'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'sender_id')
    # ### end Alembic commands ###
